# Generated by Django 5.1.6 on 2025-02-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
